# Generated by Django 6.0.1 on 2026-01-20 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_student_email_student_mobile_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimage', models.ImageField(upload_to='User_image/')),
                ('address', models.CharField(max_length=50)),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subapp.student')),
            ],
        ),
    ]
